<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ZipZap.BuildingBlocks\ZipZap.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\ZipZap.Contracts\ZipZap.Contracts.csproj" />
  </ItemGroup>

</Project>
