<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.1.2" />
    <PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ZipZap.BuildingBlocks\ZipZap.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\ZipZap.Contracts\ZipZap.Contracts.csproj" />
  </ItemGroup>

</Project>
